// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package query

import (
	"context"

	"gorm.io/gorm"
	"gorm.io/gorm/clause"
	"gorm.io/gorm/schema"

	"gorm.io/gen"
	"gorm.io/gen/field"

	"gorm.io/plugin/dbresolver"

	"go-payment-api-server/internal/domain/model"
)

func newInvoice(db *gorm.DB, opts ...gen.DOOption) invoice {
	_invoice := invoice{}

	_invoice.invoiceDo.UseDB(db, opts...)
	_invoice.invoiceDo.UseModel(&model.Invoice{})

	tableName := _invoice.invoiceDo.TableName()
	_invoice.ALL = field.NewAsterisk(tableName)
	_invoice.ID = field.NewInt64(tableName, "id")
	_invoice.CompanyID = field.NewInt64(tableName, "company_id")
	_invoice.PartnerID = field.NewInt64(tableName, "partner_id")
	_invoice.IssueDate = field.NewTime(tableName, "issue_date")
	_invoice.PaymentAmount = field.NewInt64(tableName, "payment_amount")
	_invoice.Fee = field.NewInt64(tableName, "fee")
	_invoice.FeeRate = field.NewFloat32(tableName, "fee_rate")
	_invoice.Tax = field.NewInt64(tableName, "tax")
	_invoice.TaxRate = field.NewFloat32(tableName, "tax_rate")
	_invoice.TotalAmount = field.NewInt64(tableName, "total_amount")
	_invoice.DueDate = field.NewTime(tableName, "due_date")
	_invoice.Status = field.NewString(tableName, "status")
	_invoice.CreatedAt = field.NewTime(tableName, "created_at")
	_invoice.UpdatedAt = field.NewTime(tableName, "updated_at")

	_invoice.fillFieldMap()

	return _invoice
}

type invoice struct {
	invoiceDo invoiceDo

	ALL           field.Asterisk
	ID            field.Int64
	CompanyID     field.Int64
	PartnerID     field.Int64
	IssueDate     field.Time
	PaymentAmount field.Int64
	Fee           field.Int64
	FeeRate       field.Float32
	Tax           field.Int64
	TaxRate       field.Float32
	TotalAmount   field.Int64
	DueDate       field.Time
	Status        field.String
	CreatedAt     field.Time
	UpdatedAt     field.Time

	fieldMap map[string]field.Expr
}

func (i invoice) Table(newTableName string) *invoice {
	i.invoiceDo.UseTable(newTableName)
	return i.updateTableName(newTableName)
}

func (i invoice) As(alias string) *invoice {
	i.invoiceDo.DO = *(i.invoiceDo.As(alias).(*gen.DO))
	return i.updateTableName(alias)
}

func (i *invoice) updateTableName(table string) *invoice {
	i.ALL = field.NewAsterisk(table)
	i.ID = field.NewInt64(table, "id")
	i.CompanyID = field.NewInt64(table, "company_id")
	i.PartnerID = field.NewInt64(table, "partner_id")
	i.IssueDate = field.NewTime(table, "issue_date")
	i.PaymentAmount = field.NewInt64(table, "payment_amount")
	i.Fee = field.NewInt64(table, "fee")
	i.FeeRate = field.NewFloat32(table, "fee_rate")
	i.Tax = field.NewInt64(table, "tax")
	i.TaxRate = field.NewFloat32(table, "tax_rate")
	i.TotalAmount = field.NewInt64(table, "total_amount")
	i.DueDate = field.NewTime(table, "due_date")
	i.Status = field.NewString(table, "status")
	i.CreatedAt = field.NewTime(table, "created_at")
	i.UpdatedAt = field.NewTime(table, "updated_at")

	i.fillFieldMap()

	return i
}

func (i *invoice) WithContext(ctx context.Context) IInvoiceDo { return i.invoiceDo.WithContext(ctx) }

func (i invoice) TableName() string { return i.invoiceDo.TableName() }

func (i invoice) Alias() string { return i.invoiceDo.Alias() }

func (i invoice) Columns(cols ...field.Expr) gen.Columns { return i.invoiceDo.Columns(cols...) }

func (i *invoice) GetFieldByName(fieldName string) (field.OrderExpr, bool) {
	_f, ok := i.fieldMap[fieldName]
	if !ok || _f == nil {
		return nil, false
	}
	_oe, ok := _f.(field.OrderExpr)
	return _oe, ok
}

func (i *invoice) fillFieldMap() {
	i.fieldMap = make(map[string]field.Expr, 14)
	i.fieldMap["id"] = i.ID
	i.fieldMap["company_id"] = i.CompanyID
	i.fieldMap["partner_id"] = i.PartnerID
	i.fieldMap["issue_date"] = i.IssueDate
	i.fieldMap["payment_amount"] = i.PaymentAmount
	i.fieldMap["fee"] = i.Fee
	i.fieldMap["fee_rate"] = i.FeeRate
	i.fieldMap["tax"] = i.Tax
	i.fieldMap["tax_rate"] = i.TaxRate
	i.fieldMap["total_amount"] = i.TotalAmount
	i.fieldMap["due_date"] = i.DueDate
	i.fieldMap["status"] = i.Status
	i.fieldMap["created_at"] = i.CreatedAt
	i.fieldMap["updated_at"] = i.UpdatedAt
}

func (i invoice) clone(db *gorm.DB) invoice {
	i.invoiceDo.ReplaceConnPool(db.Statement.ConnPool)
	return i
}

func (i invoice) replaceDB(db *gorm.DB) invoice {
	i.invoiceDo.ReplaceDB(db)
	return i
}

type invoiceDo struct{ gen.DO }

type IInvoiceDo interface {
	gen.SubQuery
	Debug() IInvoiceDo
	WithContext(ctx context.Context) IInvoiceDo
	WithResult(fc func(tx gen.Dao)) gen.ResultInfo
	ReplaceDB(db *gorm.DB)
	ReadDB() IInvoiceDo
	WriteDB() IInvoiceDo
	As(alias string) gen.Dao
	Session(config *gorm.Session) IInvoiceDo
	Columns(cols ...field.Expr) gen.Columns
	Clauses(conds ...clause.Expression) IInvoiceDo
	Not(conds ...gen.Condition) IInvoiceDo
	Or(conds ...gen.Condition) IInvoiceDo
	Select(conds ...field.Expr) IInvoiceDo
	Where(conds ...gen.Condition) IInvoiceDo
	Order(conds ...field.Expr) IInvoiceDo
	Distinct(cols ...field.Expr) IInvoiceDo
	Omit(cols ...field.Expr) IInvoiceDo
	Join(table schema.Tabler, on ...field.Expr) IInvoiceDo
	LeftJoin(table schema.Tabler, on ...field.Expr) IInvoiceDo
	RightJoin(table schema.Tabler, on ...field.Expr) IInvoiceDo
	Group(cols ...field.Expr) IInvoiceDo
	Having(conds ...gen.Condition) IInvoiceDo
	Limit(limit int) IInvoiceDo
	Offset(offset int) IInvoiceDo
	Count() (count int64, err error)
	Scopes(funcs ...func(gen.Dao) gen.Dao) IInvoiceDo
	Unscoped() IInvoiceDo
	Create(values ...*model.Invoice) error
	CreateInBatches(values []*model.Invoice, batchSize int) error
	Save(values ...*model.Invoice) error
	First() (*model.Invoice, error)
	Take() (*model.Invoice, error)
	Last() (*model.Invoice, error)
	Find() ([]*model.Invoice, error)
	FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Invoice, err error)
	FindInBatches(result *[]*model.Invoice, batchSize int, fc func(tx gen.Dao, batch int) error) error
	Pluck(column field.Expr, dest interface{}) error
	Delete(...*model.Invoice) (info gen.ResultInfo, err error)
	Update(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	Updates(value interface{}) (info gen.ResultInfo, err error)
	UpdateColumn(column field.Expr, value interface{}) (info gen.ResultInfo, err error)
	UpdateColumnSimple(columns ...field.AssignExpr) (info gen.ResultInfo, err error)
	UpdateColumns(value interface{}) (info gen.ResultInfo, err error)
	UpdateFrom(q gen.SubQuery) gen.Dao
	Attrs(attrs ...field.AssignExpr) IInvoiceDo
	Assign(attrs ...field.AssignExpr) IInvoiceDo
	Joins(fields ...field.RelationField) IInvoiceDo
	Preload(fields ...field.RelationField) IInvoiceDo
	FirstOrInit() (*model.Invoice, error)
	FirstOrCreate() (*model.Invoice, error)
	FindByPage(offset int, limit int) (result []*model.Invoice, count int64, err error)
	ScanByPage(result interface{}, offset int, limit int) (count int64, err error)
	Scan(result interface{}) (err error)
	Returning(value interface{}, columns ...string) IInvoiceDo
	UnderlyingDB() *gorm.DB
	schema.Tabler
}

func (i invoiceDo) Debug() IInvoiceDo {
	return i.withDO(i.DO.Debug())
}

func (i invoiceDo) WithContext(ctx context.Context) IInvoiceDo {
	return i.withDO(i.DO.WithContext(ctx))
}

func (i invoiceDo) ReadDB() IInvoiceDo {
	return i.Clauses(dbresolver.Read)
}

func (i invoiceDo) WriteDB() IInvoiceDo {
	return i.Clauses(dbresolver.Write)
}

func (i invoiceDo) Session(config *gorm.Session) IInvoiceDo {
	return i.withDO(i.DO.Session(config))
}

func (i invoiceDo) Clauses(conds ...clause.Expression) IInvoiceDo {
	return i.withDO(i.DO.Clauses(conds...))
}

func (i invoiceDo) Returning(value interface{}, columns ...string) IInvoiceDo {
	return i.withDO(i.DO.Returning(value, columns...))
}

func (i invoiceDo) Not(conds ...gen.Condition) IInvoiceDo {
	return i.withDO(i.DO.Not(conds...))
}

func (i invoiceDo) Or(conds ...gen.Condition) IInvoiceDo {
	return i.withDO(i.DO.Or(conds...))
}

func (i invoiceDo) Select(conds ...field.Expr) IInvoiceDo {
	return i.withDO(i.DO.Select(conds...))
}

func (i invoiceDo) Where(conds ...gen.Condition) IInvoiceDo {
	return i.withDO(i.DO.Where(conds...))
}

func (i invoiceDo) Order(conds ...field.Expr) IInvoiceDo {
	return i.withDO(i.DO.Order(conds...))
}

func (i invoiceDo) Distinct(cols ...field.Expr) IInvoiceDo {
	return i.withDO(i.DO.Distinct(cols...))
}

func (i invoiceDo) Omit(cols ...field.Expr) IInvoiceDo {
	return i.withDO(i.DO.Omit(cols...))
}

func (i invoiceDo) Join(table schema.Tabler, on ...field.Expr) IInvoiceDo {
	return i.withDO(i.DO.Join(table, on...))
}

func (i invoiceDo) LeftJoin(table schema.Tabler, on ...field.Expr) IInvoiceDo {
	return i.withDO(i.DO.LeftJoin(table, on...))
}

func (i invoiceDo) RightJoin(table schema.Tabler, on ...field.Expr) IInvoiceDo {
	return i.withDO(i.DO.RightJoin(table, on...))
}

func (i invoiceDo) Group(cols ...field.Expr) IInvoiceDo {
	return i.withDO(i.DO.Group(cols...))
}

func (i invoiceDo) Having(conds ...gen.Condition) IInvoiceDo {
	return i.withDO(i.DO.Having(conds...))
}

func (i invoiceDo) Limit(limit int) IInvoiceDo {
	return i.withDO(i.DO.Limit(limit))
}

func (i invoiceDo) Offset(offset int) IInvoiceDo {
	return i.withDO(i.DO.Offset(offset))
}

func (i invoiceDo) Scopes(funcs ...func(gen.Dao) gen.Dao) IInvoiceDo {
	return i.withDO(i.DO.Scopes(funcs...))
}

func (i invoiceDo) Unscoped() IInvoiceDo {
	return i.withDO(i.DO.Unscoped())
}

func (i invoiceDo) Create(values ...*model.Invoice) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Create(values)
}

func (i invoiceDo) CreateInBatches(values []*model.Invoice, batchSize int) error {
	return i.DO.CreateInBatches(values, batchSize)
}

// Save : !!! underlying implementation is different with GORM
// The method is equivalent to executing the statement: db.Clauses(clause.OnConflict{UpdateAll: true}).Create(values)
func (i invoiceDo) Save(values ...*model.Invoice) error {
	if len(values) == 0 {
		return nil
	}
	return i.DO.Save(values)
}

func (i invoiceDo) First() (*model.Invoice, error) {
	if result, err := i.DO.First(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invoice), nil
	}
}

func (i invoiceDo) Take() (*model.Invoice, error) {
	if result, err := i.DO.Take(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invoice), nil
	}
}

func (i invoiceDo) Last() (*model.Invoice, error) {
	if result, err := i.DO.Last(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invoice), nil
	}
}

func (i invoiceDo) Find() ([]*model.Invoice, error) {
	result, err := i.DO.Find()
	return result.([]*model.Invoice), err
}

func (i invoiceDo) FindInBatch(batchSize int, fc func(tx gen.Dao, batch int) error) (results []*model.Invoice, err error) {
	buf := make([]*model.Invoice, 0, batchSize)
	err = i.DO.FindInBatches(&buf, batchSize, func(tx gen.Dao, batch int) error {
		defer func() { results = append(results, buf...) }()
		return fc(tx, batch)
	})
	return results, err
}

func (i invoiceDo) FindInBatches(result *[]*model.Invoice, batchSize int, fc func(tx gen.Dao, batch int) error) error {
	return i.DO.FindInBatches(result, batchSize, fc)
}

func (i invoiceDo) Attrs(attrs ...field.AssignExpr) IInvoiceDo {
	return i.withDO(i.DO.Attrs(attrs...))
}

func (i invoiceDo) Assign(attrs ...field.AssignExpr) IInvoiceDo {
	return i.withDO(i.DO.Assign(attrs...))
}

func (i invoiceDo) Joins(fields ...field.RelationField) IInvoiceDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Joins(_f))
	}
	return &i
}

func (i invoiceDo) Preload(fields ...field.RelationField) IInvoiceDo {
	for _, _f := range fields {
		i = *i.withDO(i.DO.Preload(_f))
	}
	return &i
}

func (i invoiceDo) FirstOrInit() (*model.Invoice, error) {
	if result, err := i.DO.FirstOrInit(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invoice), nil
	}
}

func (i invoiceDo) FirstOrCreate() (*model.Invoice, error) {
	if result, err := i.DO.FirstOrCreate(); err != nil {
		return nil, err
	} else {
		return result.(*model.Invoice), nil
	}
}

func (i invoiceDo) FindByPage(offset int, limit int) (result []*model.Invoice, count int64, err error) {
	result, err = i.Offset(offset).Limit(limit).Find()
	if err != nil {
		return
	}

	if size := len(result); 0 < limit && 0 < size && size < limit {
		count = int64(size + offset)
		return
	}

	count, err = i.Offset(-1).Limit(-1).Count()
	return
}

func (i invoiceDo) ScanByPage(result interface{}, offset int, limit int) (count int64, err error) {
	count, err = i.Count()
	if err != nil {
		return
	}

	err = i.Offset(offset).Limit(limit).Scan(result)
	return
}

func (i invoiceDo) Scan(result interface{}) (err error) {
	return i.DO.Scan(result)
}

func (i invoiceDo) Delete(models ...*model.Invoice) (result gen.ResultInfo, err error) {
	return i.DO.Delete(models)
}

func (i *invoiceDo) withDO(do gen.Dao) *invoiceDo {
	i.DO = *do.(*gen.DO)
	return i
}
