// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameInvoice = "invoices"

// Invoice mapped from table <invoices>
type Invoice struct {
	ID            int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CompanyID     int64      `gorm:"column:company_id;type:bigint;not null;index:company_id,priority:1" json:"company_id"`
	PartnerID     int64      `gorm:"column:partner_id;type:bigint;not null;index:partner_id,priority:1" json:"partner_id"`
	IssueDate     time.Time  `gorm:"column:issue_date;type:date;not null" json:"issue_date"`
	PaymentAmount int64      `gorm:"column:payment_amount;type:bigint;not null" json:"payment_amount"`
	Fee           int64      `gorm:"column:fee;type:bigint;not null" json:"fee"`
	FeeRate       float32    `gorm:"column:fee_rate;type:float;not null" json:"fee_rate"`
	Tax           int64      `gorm:"column:tax;type:bigint;not null" json:"tax"`
	TaxRate       float32    `gorm:"column:tax_rate;type:float;not null" json:"tax_rate"`
	TotalAmount   int64      `gorm:"column:total_amount;type:bigint;not null" json:"total_amount"`
	DueDate       time.Time  `gorm:"column:due_date;type:date;not null" json:"due_date"`
	Status        *string    `gorm:"column:status;type:enum('pending','processing','paid','error');default:pending" json:"status"`
	CreatedAt     *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt     *time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Invoice's table name
func (*Invoice) TableName() string {
	return TableNameInvoice
}
