// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePartner = "partners"

// Partner mapped from table <partners>
type Partner struct {
	ID         int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CompanyID  int64      `gorm:"column:company_id;type:bigint;not null;index:company_id,priority:1" json:"company_id"`
	Name       *string    `gorm:"column:name;type:varchar(255)" json:"name"`
	CeoName    *string    `gorm:"column:ceo_name;type:varchar(255)" json:"ceo_name"`
	Phone      *string    `gorm:"column:phone;type:varchar(20)" json:"phone"`
	PostalCode *string    `gorm:"column:postal_code;type:varchar(10)" json:"postal_code"`
	Address    *string    `gorm:"column:address;type:text" json:"address"`
	CreatedAt  *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt  *time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName Partner's table name
func (*Partner) TableName() string {
	return TableNamePartner
}
