// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNamePartnerBankAccount = "partner_bank_accounts"

// PartnerBankAccount mapped from table <partner_bank_accounts>
type PartnerBankAccount struct {
	ID                int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	PartnerID         int64      `gorm:"column:partner_id;type:bigint;not null;index:partner_id,priority:1" json:"partner_id"`
	BankName          *string    `gorm:"column:bank_name;type:varchar(255)" json:"bank_name"`
	BranchName        *string    `gorm:"column:branch_name;type:varchar(255)" json:"branch_name"`
	AccountNumber     *string    `gorm:"column:account_number;type:varchar(50)" json:"account_number"`
	AccountHolderName *string    `gorm:"column:account_holder_name;type:varchar(255)" json:"account_holder_name"`
	CreatedAt         *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt         *time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName PartnerBankAccount's table name
func (*PartnerBankAccount) TableName() string {
	return TableNamePartnerBankAccount
}
