// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import (
	"time"
)

const TableNameUser = "users"

// User mapped from table <users>
type User struct {
	ID        int64      `gorm:"column:id;type:bigint;primaryKey;autoIncrement:true" json:"id"`
	CompanyID int64      `gorm:"column:company_id;type:bigint;not null;index:company_id,priority:1" json:"company_id"`
	Name      *string    `gorm:"column:name;type:varchar(255)" json:"name"`
	Email     *string    `gorm:"column:email;type:varchar(255);uniqueIndex:email,priority:1" json:"email"`
	Password  *string    `gorm:"column:password;type:text" json:"password"`
	CreatedAt *time.Time `gorm:"column:created_at;type:timestamp;default:CURRENT_TIMESTAMP" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at;type:timestamp;not null;default:CURRENT_TIMESTAMP" json:"updated_at"`
}

// TableName User's table name
func (*User) TableName() string {
	return TableNameUser
}
